//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csillám_kezelőfelület.ReklamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReklamService.IServiceReklam")]
    public interface IServiceReklam {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReklam/ReklamEmail", ReplyAction="http://tempuri.org/IServiceReklam/ReklamEmailResponse")]
        bool ReklamEmail(string adat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReklam/ReklamEmail", ReplyAction="http://tempuri.org/IServiceReklam/ReklamEmailResponse")]
        System.Threading.Tasks.Task<bool> ReklamEmailAsync(string adat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReklam/Hibalog", ReplyAction="http://tempuri.org/IServiceReklam/HibalogResponse")]
        bool Hibalog(string adat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceReklam/Hibalog", ReplyAction="http://tempuri.org/IServiceReklam/HibalogResponse")]
        System.Threading.Tasks.Task<bool> HibalogAsync(string adat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceReklamChannel : Csillám_kezelőfelület.ReklamService.IServiceReklam, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceReklamClient : System.ServiceModel.ClientBase<Csillám_kezelőfelület.ReklamService.IServiceReklam>, Csillám_kezelőfelület.ReklamService.IServiceReklam {
        
        public ServiceReklamClient() {
        }
        
        public ServiceReklamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceReklamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReklamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReklamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReklamEmail(string adat) {
            return base.Channel.ReklamEmail(adat);
        }
        
        public System.Threading.Tasks.Task<bool> ReklamEmailAsync(string adat) {
            return base.Channel.ReklamEmailAsync(adat);
        }
        
        public bool Hibalog(string adat) {
            return base.Channel.Hibalog(adat);
        }
        
        public System.Threading.Tasks.Task<bool> HibalogAsync(string adat) {
            return base.Channel.HibalogAsync(adat);
        }
    }
}
