

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AdatKezelő
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class csillamponimenhelyDBEntities : DbContext
{
    public csillamponimenhelyDBEntities()
        : base("name=csillamponimenhelyDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ADOMANY> ADOMANY { get; set; }

    public virtual DbSet<ALLAT> ALLAT { get; set; }

    public virtual DbSet<ELEDEL> ELEDEL { get; set; }

    public virtual DbSet<KENNEL> KENNEL { get; set; }

    public virtual DbSet<UGYFEL> UGYFEL { get; set; }

    public virtual DbSet<user> user { get; set; }

}

}

