//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdatKezelő
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEDEL
    {
        public string FAJTA { get; set; }
        public Nullable<int> RAKTARON { get; set; }
    
        public virtual KENNEL KENNEL { get; set; }
    }
}
