//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdatKezelő
{
    using System;
    using System.Collections.Generic;
    
    public partial class KENNEL
    {
        public KENNEL()
        {
            this.ALLAT = new HashSet<ALLAT>();
        }
    
        public string TIPUS { get; set; }
        public Nullable<int> SZABAD { get; set; }
        public Nullable<int> FOGLALT { get; set; }
        public int MAXDARAB { get; set; }
    
        public virtual ICollection<ALLAT> ALLAT { get; set; }
        public virtual ELEDEL ELEDEL { get; set; }
    }
}
