//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdatKezelő
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGYFEL
    {
        public UGYFEL()
        {
            this.ADOMANY = new HashSet<ADOMANY>();
            this.ALLAT = new HashSet<ALLAT>();
        }
    
        public string VEZETEKNEV { get; set; }
        public string KERESZTNEV { get; set; }
        public Nullable<decimal> IRSZ { get; set; }
        public string VAROS { get; set; }
        public string UTCA { get; set; }
        public Nullable<decimal> HAZSZAM { get; set; }
        public Nullable<decimal> TELEFON { get; set; }
        public System.Guid UGYFELID { get; set; }
        public string EMAIL { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
        public Nullable<System.DateTime> REGDATUM { get; set; }
    
        public virtual ICollection<ADOMANY> ADOMANY { get; set; }
        public virtual ICollection<ALLAT> ALLAT { get; set; }
    }
}
